### ISSUE TITLE
Include explicit dependencies

### ISSUE THREAD

**Issue by jokochems** [pommes-public/pommesdata#129]
## Problem description
Some of the dependencies are a bit outdated as they have not been regularly updated in the course of the development. In order to allow for reuse, an explicit version of dependencies should be included until dependencies are updated.

## Suggestion
Include an explicit version of dependencies.

**Comment by maurerle** [comment]
With this version, one can execute the script if additionally:
1. when2heat csv is downloaded from here: https://data.open-power-system-data.org/when2heat/2022-02-22
2. ee_powerplants_29102021.csv is received from @jokochems 
3. folder graphics and prepared_data are created in advance
4. I needed additional changes though:
replace:
`conv_de_new['commissioned_last'] = conv_de_new['commissioned'].astype(int)` with `conv_de_new['commissioned_last'] = conv_de_new['commissioned'].fillna(0).astype(int)` and

replace:
`min_load_ts[min_load_ts < 0] = 0` with `min_load_ts = min_load_ts.clip(lower=0)`

The `prepared_data` output folder has a size of 1.5GB.
With this - I am able to successfully run `run_pommes_dispatch` from pommesdispatch after replacing `gurobi` with `glpk` in config.yml :tada:
